build:
    project_setup:
        before:
            -
                command: meteor
                background: true
            -
                command: npm install -g chimp
                background: false
    tests:
        override:
            - 'chimp --chai'
